config/routes.rb
Homework::Application.routes.draw do
  resources :users do
    resources :equipments
    resources :orders
  end
  resources :equipments do
    resources :orders
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :equipments, only: [:new, :create]

  match '/signin', to:'sessions#new'
  match '/signup', to:'users#new'
  match '/signout', to:'sessions#destroy', via: :delete

  root to:'home_pages#home'

  match '/manager', to: 'home_pages#manager'
  match '/users/:user_id/manager_orders', to: 'home_pages#manager_orders'
  match '/manager/:order_id/order', to: 'home_pages#check_order'
  match '/manager/:order_id/check', to: 'home_pages#check', via: :put
  match '/search', to: 'home_pages#search'

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  belongs_to :user
  has_many :orders

  attr_accessible :able_end_time, :able_start_time, :belong_to_institution, :count, :detail, :name, :number, :status, :owner, :price, :user_id

  validates :user_id, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :equipment
  attr_accessible :buy_date, :check_status, :equipment_name, :equipment_num, :over_status, :price, :quantity, :use_end_date, :use_start_date, :user_name
  attr_accessible :user_id, :equipment_id, :message

  validates :user_id, :equipment_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders, dependent: :destroy
  has_many :equipments
  attr_accessible :email, :institution, :money, :password, :phone, :type, :name, :remmember_token
  #has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format:{ with:VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
  validates :email, :name, :password, presence: true

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  def signed_in_user
    redirect_to signin_path, notice: 'Please sign in.' unless signed_in?
  end
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  before_filter :signed_in_user, except: [:show]

  def index
    @user = User.find(params[:user_id])
    if !@user.nil?
      @equipments = @user.equipments
    end
  end

  def new
    @equipment = Equipment.new
    @user = User.find(params[:user_id])
    @equipment.owner = @user.name
    @equipment.belong_to_institution = @user.institution

  end

  def create
    @equipment = current_user.equipments.build(params[:equipment])

    if @equipment.save
      flash[:success] = 'new equipments success!!'
      redirect_to user_equipments_path(current_user)
    else
      redirect_to new_equipment_path
    end
  end

  def edit
    @equipment = Equipment.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @equipment = Equipment.find(params[:id])

    if @equipment.update_attributes(params[:equipment])
      flash[:success] = 'equipment updated success!!'
      redirect_to user_equipments_path(@user)
    else
      flash.now[:error] = 'equipment updated fail.'
      render 'edit'
    end
  end

  def destroy
    @equipment = Equipment.find(params[:id])
    if @equipment.user.eql?current_user
      @equipment.destroy
      redirect_to user_equipments_path(current_user)
    else
      flash[:error] = "equipment destroy error"
      redirect_to user_equipments_path(current_user)
    end
  end

  private
  def signed_in_user
    redirect_to signin_path, notice: 'Please sign in.' unless signed_in?
  end
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def home
    @equipments = Equipment.all

    respond_to do |format|
      format.html #home.html.erb
    end
  end
  def manager

  end
  def manager_orders
    @user = User.find(params[:user_id])
    
    if current_user?(@user)
      @equipments = @user.equipments
      @orders = Array.new
      @equipments.each { |equipment| @orders = @orders + equipment.orders }

    else
      flash[:error] = 'user is not correct!'
      redirect_to manager_path
    end
  end
  def search
    @equipments = Equipment.find_all_by_name(params[:equipment][:name])
    #flash[:notice] = params[:equipment][:name]
    respond_to do |format|
      format.html { render 'home'}
    end
  end
  def check_order
    @order = Order.find(params[:order_id])
  end
  def check
    @order = Order.find(params[:order_id])

    if @order.update_attributes(params[:order])
      flash[:success] = 'confirmed success'
      redirect_to :controller => :home_pages, :action => :manager_orders, :user_id => current_user.id
    else
      flash[:error] = 'confirmed fail'
      redirect_to :controller => :home_pages, :action => :manager_orders, :user_id => current_user.id
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :signed_in_user

  def index
    if !params[:user_id].nil?
      @user = User.find(params[:user_id])
      @orders = @user.orders
    elsif !params[:equipment_id].nil?
      @equipment = Equipment.find(params[:equipment_id])
      @orders = @equipment.orders
    else
      flash[:error] = 'no such pages'
      redirect_to root_path
    end
  end
  def new
    @equipment = Equipment.find(params[:equipment_id])
    if !@equipment.nil?
      @order = Order.new
      #@order.equipment = @equipment
      @order.equipment_name= @equipment.name
      @order.equipment_num= @equipment.number
      @order.use_start_date= @equipment.able_start_time
      @order.use_end_date= @equipment.able_end_time
    else
      flash[:error] = 'no equipments selected!'
      redirect_to root_path
    end
  end
  def create
    @order = current_user.orders.build(params[:order])
    @order.equipment = Equipment.find(params[:equipment_id])

    if @order.save
      flash[:success] = 'new orders created!'
      redirect_to user_orders_path(current_user)
    else
      flash[:error] = 'orders created fail!'
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.password.eql?(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user, only:  [:edit, :update]
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      sign_in @user
      flash[:success] = 'Welcome sign up!'
      redirect_to @user
    else
      flash.now[:error] = 'sign up error!'
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def edit
    #@user = User.find(params[:id])
  end

  def update
    #@user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      flash[:success] = 'Profile updated'
      sign_in @user
      redirect_to @user
    else
      flash.now[:error] = 'update error!'
      render 'edit'
    end
  end

  def destroy
  end

  private
    def signed_in_user
      redirect_to signin_path, notice: 'Please sign in.' unless signed_in?
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  def current_user=(user)
    @current_user = user
  end
  def current_user
    @current_user = @current_user || User.find_by_remember_token(cookies[:remember_token])
  end
  def signed_in?
    !current_user.nil?
  end
  def sign_out
    self.current_user =nil
    cookies.delete(:remember_token)
  end
  def current_user?(user)
    user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/equipments/_form.html.erb
<%= form_for([current_user, @equipment]) do |f| %>
    <%= f.label :name, "仪器名称：" %>
    <%= f.text_field :name %>
    <%= f.label :number, "仪器编号：" %>
    <%= f.text_field :number %>
    <%= f.label :belong_to_institution, "所属单位："%>
    <%= f.text_field :belong_to_institution %>
    <%= f.label :owner, "管理人员：" %>
    <%= f.text_field :owner %>
    <%= f.label :detail, "功能：" %>
    <%= f.text_field :detail %>
    <%= f.label :price, "价格：" %>
    <%= f.text_field :price %>
    <h2>可用时间段</h2>
    <%= f.label :able_start_time, "起始时间：" %>
    <%= f.datetime_select :able_start_time %>
    <%= f.label :able_end_time, "结束时间：" %>
    <%= f.datetime_select :able_end_time %>
    <br>
    <%= f.submit "提交" %>
<% end %>

app/views/equipments/edit.html.erb
<h1>编辑仪器</h1>
<%= render 'form' %>
<%= link_to '返回', user_equipments_path %>

app/views/equipments/index.html.erb
<h1>我的仪器</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th>所属单位</th>
    <th>仪器名称</th>
    <th>仪器编号</th>
    <th>管理人员</th>
    <th>功能</th>
    <th>价格</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @equipments.each do |e| %>
      <tr>
        <td><%= e.belong_to_institution %></td>
        <td><%= e.name %></td>
        <td><%= e.number %></td>
        <td><%= e.owner %></td>
        <td><%= e.detail %></td>
        <td><%= e.price %></td>
        <td><%= link_to '编辑', edit_user_equipment_path(current_user, e) %></td>
        <td><%= link_to '删除', user_equipment_path(current_user, e), :method => :delete, :confirm => "删除仪器？" %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to '返回', manager_path %>

app/views/equipments/new.html.erb
<h1>添加仪器</h1>
<%= form_for @equipment, :url => user_equipments_path(@user) do |f| %>
    <%= f.label :name, "仪器名称：" %>
    <%= f.text_field :name %>
    <%= f.label :number, "仪器编号：" %>
    <%= f.text_field :number %>
    <%= f.label :belong_to_institution, "所属单位："%>
    <%= f.text_field :belong_to_institution %>
    <%= f.label :owner, "管理人员：" %>
    <%= f.text_field :owner %>
    <%= f.label :detail, "功能：" %>
    <%= f.text_field :detail %>
    <%= f.label :price, "价格：" %>
    <%= f.text_field :price %>
    <h2>可用时间段</h2>
    <%= f.label :able_start_time, "起始时间：" %>
    <%= f.datetime_select :able_start_time %>
    <%= f.label :able_end_time, "结束时间：" %>
    <%= f.datetime_select :able_end_time %>
    <br>
    <%= f.submit "提交" %>
<% end %>
<%= link_to "返回", manager_path %>

app/views/home_pages/check_order.html.erb
<h1>订单审核</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th>用户姓名</th>
    <th>所属机构</th>
    <th>预定仪器名称</th>
    <th>预定仪器编号</th>
    <th>预约使用开始时间</th>
    <th>预约使用结束时间</th>
  </tr>
  </thead>
  <tbody>
    <% if !@order.nil? %>
      <tr>
        <td><%= @order.user.name %></td>
        <td><%= @order.user.institution %></td>
        <td><%= @order.equipment_name %></td>
        <td><%= @order.equipment_num %></td>
        <td><%= @order.use_start_date %></td>
        <td><%= @order.use_end_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= form_for @order,:as => :order, :url => { controller: :home_pages, action: :check, :order_id => @order.id }, :method => :put do |f| %>
    <%= f.label :check_status, "通过：" %>
    <%= f.check_box :check_status %>
    <%= f.label :message, "审核信息：" %>
    <%= f.text_field :message %><br>
    <%= f.submit "确认" %>
<% end %>
<%= link_to "返回", :controller => "home_pages", :action => "manager_orders", :user_id => current_user.id %>

app/views/home_pages/home.html.erb
<h1>首页</h1>
<%= form_for Equipment.new, :url => search_path, :method => :get do |f|%>
    <%= f.label :name, "仪器名称" %>
    <%= f.text_field :name %>
    <%= f.submit "搜索" %>
<% end %>
<% if !@equipments.first.nil? %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>所属单位</th>
        <th>设备名称</th>
        <th>设备编号</th>
        <th>功能</th>
        <th>价格</th>
        <th>管理人员</th>
        <th>预约状态</th>
      </tr>
      </thead>
      <tbody>
      <% @equipments.each do |equipment| %>
          <tr>
            <td><%= equipment.belong_to_institution %></td>
            <td><%= equipment.name %></td>
            <td><%= equipment.number %></td>
            <td><%= equipment.detail %></td>
            <td><%= equipment.price %></td>
            <td><%= equipment.owner %></td>
            <td><%= link_to "预约", new_equipment_order_path(equipment) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>
<!--<%= params.inspect %>-->

app/views/home_pages/manager.html.erb
<div class="row">
  <div class="span2">
    <%= render 'layouts/for_manager' %>
  </div>

</div>

app/views/home_pages/manager_orders.html.erb
<h1>管理员订单</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th>用户姓名</th>
    <th>所属机构</th>
    <th>预定仪器名称</th>
    <th>预定仪器编号</th>
    <th>预约使用开始时间</th>
    <th>预约使用结束时间</th>
    <th>订单状态</th>
  </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
    <tr>
      <td><%= order.user.name %></td>
      <td><%= order.user.institution %></td>
      <td><%= order.equipment_name %></td>
      <td><%= order.equipment_num %></td>
      <td><%= order.use_start_date %></td>
      <td><%= order.use_end_date %></td>
      <% if order.check_status.nil? %>
        <td><%= link_to "审核", controller: "home_pages", action: :check_order, order_id: order.id %></td>
      <% elsif order.check_status %>
        <td><span id="check_success">已审核，预约成功</span></td>
      <% else %>
        <td id="check_fail">已审核，预约失败</td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to '返回', manager_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">

</footer>

app/views/layouts/_for_manager.html.erb
<ul class="nav nav-list">
  <li class="nav-header">我是管理员</li>
  <li><%= link_to "我的仪器", user_equipments_path(current_user) %></li>
  <li><%= link_to "添加仪器", new_user_equipment_path(current_user) %></li>
  <li><%= link_to "订单审核", :controller => "home_pages", :action => "manager_orders", :user_id => current_user.id %></li>
</ul>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "首页", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to '浏览仪器', root_path %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                我的帐号<b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "我的订单", user_orders_path(current_user) %></li>
                <li><%= link_to "我是管理员", manager_path %></li>
                <li><%= link_to "个人信息", current_user %></li>
                <li class="divider"></li>
                <li><%= link_to "退出", signout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "登录", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homework</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>

</body>
</html>

app/views/orders/index.html.erb
<h1>我的订单</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th>仪器名称</th>
    <th>仪器编号</th>
    <th>预约起始时间</th>
    <th>预约结束时间</th>
    <th>审核状态</th>
    <th>审核信息</th>
  </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
      <tr>
        <td><%= order.equipment_name %></td>
        <td><%= order.equipment_num %></td>
        <td><%= order.use_start_date %></td>
        <td><%= order.use_end_date %></td>
        <% if order.check_status.nil? %>
        <td>未审核</td>
        <% elsif order.check_status %>
        <td id="check_success">已审核，预约成功</td>
        <% else %>
        <td id="check_fail">已审核，预约失败</td>
        <% end %>
        <td><%= order.message %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<h1>创建订单</h1>
<%= form_for [@equipment, @order] do |f| %>
    <%= f.label :equipment_name, "仪器名称：" %>
    <%= f.text_field :equipment_name %>
    <%= f.label :equipment_num, "仪器编号：" %>
    <%= f.text_field :equipment_num %>
    <%= f.label :use_start_date, "预约起始时间：" %>
    <%= f.datetime_select :use_start_date %>
    <%= f.label :use_end_date, "预约结束时间：" %>
    <%= f.datetime_select :use_end_date %>
    <br>
    <%= f.submit '提交订单' %>
<% end %>
<%= link_to "返回", root_path %>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>用户编辑</h1>
<%= form_for @user do |f| %>
    <div>
      <%= f.label :email, "邮箱：" %>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :name, "用户名：" %>
      <%= f.text_field :name %>
    </div>
    <%= f.label :phone, "电话：" %>
    <%= f.text_field :phone %>
    <%= f.label :institution, "所属单位："  %>
    <%= f.text_field :institution %>
    <div>
      <%= f.submit "更新" %>
    </div>
<% end %>
<%= link_to "返回", user_path %>

app/views/users/new.html.erb
<h1>注册</h1>
<%= form_for @user, :url => users_path do |f| %>
    <%= label_tag "user_email", "邮箱：" %>
    <%= f.text_field :email %>
    <label for="user_name">用户名：</label>
    <%= f.text_field :name %>
    <label for="user_password">密码：</label>
    <%= f.password_field :password %>
    <%= f.submit "注册" %>
<% end %>

app/views/users/show.html.erb
<h1>显示</h1>
<p id="notice"><%= notice %></p>
<% if signed_in? %>

    <label>用户名：<%= current_user.name%></label><br>
    <label>邮箱：<%= current_user.email%></label><br>
    <label>联系方式：<%= current_user.phone %></label><br>
    <label>所属单位：<%= current_user.institution %></label>

<% end %>
<br>
<%= link_to '返回', '/' %>
<%= link_to '编辑', edit_user_path %>